### ISSUE TITLE
Post code for side-by-side radio example?

### ISSUE THREAD

**Issue by pm0kjp** [susom/redcap-em-shazam#32]
Hi!  I'm writing from the Children's Hospital of Philadelphia.  I have a couple of matrix radio button questions very similar to your "Or, you can go crazy as in this side-by-side radio example" frequency / severity image.  But I can't figure out the html!  

* Are you using individual questions, or a matrix?
* How are you preventing the label from showing up over each radio button?

If the html for this example is somewhere and I'm missing it, I apologize, please point me in the right direction!

**Comment by 123andy** [comment]
Here is some HTML from the project - or so I think it is the right project - been many years... I don't think we are using matrixes at all.

```html
<table class='tele'>
    <tr class='h_row'>
        <th></th>
        <th class="t_row">
            <table class="group1">
                <tr>
                    <td colspan=5>Average frequency of occurrence</td>
                </tr>
                <tr>
                    <td>Never</td>
                    <td>Monthly</td>
                    <td>Weekly</td>
                    <td>Daily</td>
                    <td>Hourly</td>
                </tr>
            </table>
        </th>
        <th class="t_row">
            <table class="group2">
                <tr>
                    <td colspan=4>Severity of the problem</td>
                </tr>
                <tr>
                    <td>Not a problem</td>
                    <td>slight problem</td>
                    <td>moderate problem</td>
                    <td>severe problem</td>
                </tr>
            </table>
        </th>
    </tr>
    <tr>
        <th>1. Self-biting</th>
        <td><span class='shazam'>self_biting_avg</span></td>
        <td><span class='shazam'>self_biting_sev</span></td>
    </tr>
    <tr>
        <th>2. Head hitting</th>
        <td><span class='shazam'>head_hitting_avg</span></td>
        <td><span class='shazam'>head_hitting_sev</span></td>
    </tr>
    <tr>
        <th>3. Body hitting (except for the head) with own hand </th>
        <td><span class='shazam'>body_hitting_avg</span></td>
        <td><span class='shazam'>body_hitting_sev</span></td>
    </tr>
    <tr>
        <th>4. Self-scratching</th>
        <td><span class='shazam'>self_scratching_avg</span></td>
        <td><span class='shazam'>self_scratching_sev</span></td>
    </tr>
    <tr>
        <th>5. Pica (ingesting non-food items)</th>
        <td><span class='shazam'>pica_avg</span></td>
        <td><span class='shazam'>pica_sev</span></td>
    </tr>
    <tr>
        <th>6. Inserting objects in nose, ears etc.</th>
        <td><span class='shazam'>inserting_objects_avg</span></td>
        <td><span class='shazam'>inserting_objects_sev</span></td>
    </tr>
    <tr>
        <th>7. Hair pulling (tearing out patches of hair)</th>
        <td><span class='shazam'>hair_pulling_avg</span></td>
        <td><span class='shazam'>hair_pulling_sev</span></td>
    </tr>
    <tr>
        <th>8. Overall self-injurious behavior </th>
        <td><span class='shazam'>teeth_grinding_avg</span></td>
        <td><span class='shazam'>teeth_grinding_sev</span></td>
    </tr>
</table>
```


CSS:
```css
td.questionnum, td.questionnummatrix {display:none !important; }
        .shazam .smalllink {display:none;}

        table.tele,     table.tele td {
            /*border: 1px solid red; */
            width: 100%;
            border-spacing: 0px;
            border-collapse: separate;
        }

        table.group1, table.group2 {
            border-spacing: 0px;
            border-collapse: separate;
        }
        table.group1 td, table.group2 td {
            font-size:smaller;
            text-align:center;
            overflow:hidden;
            text-overflow:ellipsis;
        }
        table.group1 td {min-width: 50px; width:50px; max-width: 50px;}
        table.group2 td {width:65px; min-width: 65px; max-width: 65px;}

        table.group1 tr:last-child td, table.group2 tr:last-child td {
            height: 40px;
            vertical-align:bottom;
            border-bottom: 1px solid #333;
        }

        table.group1 tr:first-child td, table.group2 tr:first-child td {
            font-weight: bold;
        }

        /* Add a border to the right of the second row */
        table.tele td:nth-child(2), table.tele th:nth-child(2) {
            border-right: 1px solid #333;
        }

        /* Hide the spacer in the top row */
        table.group1 td, table.group2 td {
            border-right: none !important;
        }

        table.tele .shazam span.choicehoriz {
            /*padding: 1px 20px 1px 10px;*/
            display: inline-block;
            height:100%;
            padding: 0px;
            margin: 0px;
            width:49px; min-width: 49px; max-width: 49px;
        }

        table.tele tr td:last-child .shazam span.choicehoriz {
            width:64px; min-width: 64px; max-width: 64px;
        }

        .shazam span.choicehoriz input {
            padding: 0 0 0 0px;
            margin: 13px 0 0 22px;
        }

        /* Makes the first column wider to fit all the text label */
        table.tele tr th:first-child {
            min-width:265px;
            vertical-align:middle;
        }

        table.tele tr td, table.tele tr th, table.tele td span.shazam {
            height: 46px; min-height: 46px; vertical-align:middle
        }

        table.tele tr td span {display:block;}
        table.tele tr:nth-child(even) th {background-color: #eee;}
        table.tele tr:nth-child(even) td span {background-color: #eee;}
```
